name: Lint commit messages
on:
  push:
  #push:
  #  branches:
  #    - master
 ## pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
              
      - run: echo $GITHUB_TOKEN
 
