name: Lint commit messages
on:
  push:
    branches:
    - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
              
      - run: echo $GITHUB_CONTEXT
        env:
           GITHUB_CONTEXT: ${{ tojson(github) }}
