name: Lint commit messages
on:
  push:
  #push:
  #  branches:
  #    - master
 ## pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: use my js action
        uses: yanjingzhu/FirstJSAction@master
        with: 
          who-to-greet: "yan jingzhu"
        
      - run: echo "Hello"
        if: always()
