# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  check_suite:
  #push:
  #   paths:
  #     - '**/main.yml'

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      # env context is empty at the beginning
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      # set system ProgramFiles value to env ProgramFilesPath
      - name: set env ProgramFiles
        shell: cmd    
        run: |
           echo %programfiles%
           echo ::set-env name=ProgramFilesPath::%programfiles%
      # check env context again, now include ProgramFilesPath
      - name: Dump env context 2
        env:
          ENV_CONTEXT1: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      # Now you can use env.ProgramFilesPath
      - name: Cache git
        uses: actions/cache@v1
        with:
          path: ${{ env.ProgramFilesPath }}\Git
          key: ${{ runner.os }}-git-${{ hashFiles('**/main.yml') }}-1-
