# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  push:
     paths:
       - '**/main.yml'

jobs:
  build:
    env: 
      key1: ${{secrets.test2 }}
    runs-on: macos-latest
     steps: 
    - run:   echo hello
      if: ${{env.key1}} == 'aaa'


