# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  push:
     paths:
       - '**/main.yml'

jobs:
  build:

    runs-on: macos-latest

    steps: 
    - run: csrutil status
     


