# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  push:
     paths:
       - '**/main.yml'

jobs:
  build:
    env: 
      key1: ${{secrets.test2}} 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - run: echo $key1
      if: ${{env.key1}} == 'aaa'


