# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  push:
     paths:
       - '**/main.yml'

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      - name: set env ProgramFiles
        shell: cmd    
        run: |
           echo %programfiles%
           echo ::set-env name=ProgramFilesPath::%programfiles%
      - name: Dump env context 2
        env:
          ENV_CONTEXT1: ${{ toJson(env) }}
        run: write-host "$env:ENV_CONTEXT1"
      - name: Cache git
        uses: actions/cache@v1
        with:
          path: ${{ env.ProgramFilesPath }}\Git
          key: ${{ runner.os }}-git-${{ hashFiles('**/main.yml') }}-1-
