# This is a basic workflow to help you get started with Actions ss

name: CI

on:
  push:
     paths:
       - '**/main.yml'



jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      - name: set env ProgramFiles
        shell: cmd    
        run: |
           echo %programfiles%
           echo ::set-env name=ProgramFilesPath::%programfiles%
      - name: Dump env context 2
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
