# This is a basic workflow to help you get started with Actions ss

name: CI

# Controls when the action will run. Triggers the ssworkflow on push or pull request1
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Count Lines of Code (cloc)
      uses: zhuorg/cloc-action@4b81b14
