Name: get secrets variable name from another env
on: push
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: |
         echo "::set-env name=ENVIRONMENT::PROD"
    - run: |
         echo $ENVIRONMENT
         echo ${{ secrets[$ENVIRONMENT] }}
      env: 
        env_name: ${{secrets.PROD }}
