name: get secrets variable name from another env
on: push
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: echo "::set-env name=ENVIRONMENT::PROD"
      env: 
        environment: ${{secrets.PROD}}
    - name: Set env to non production 
      if: "!endsWith(github.ref, '/master')"
      run: echo "::set-env name=ENVIRONMENT::TEST"
      env: 
        environment: ${{secrets.TEST}}
