name: get secrets variable name from another env
on: check_suite
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: echo $environment
      env: 
        environment: ${{secrets.PROD}}
    - name: Set env to non production 
      if: "!endsWith(github.ref, '/master')"
      run: echo $environment
      env: 
        environment: ${{secrets.TEST}}
